#!/usr/bin/env bash
set -euo pipefail
repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
require() { rg -q -- "$1" "$2" || { echo "FAIL: $1 in $2" >&2; exit 1; }; }
forbid() { ! rg -q -- "$1" "$2" || { echo "FAIL: unexpected $1 in $2" >&2; exit 1; }; }
require 'target: "menu"' "$repo/versions/default/shell.qml"
require 'target: "clipboard"' "$repo/versions/default/shell.qml"
require 'target: "capture"' "$repo/versions/default/shell.qml"
require 'SelectableList' "$repo/versions/default/panels/OmarchyMenuPanel.qml"
require 'id: leftPane' "$repo/versions/default/panels/ClipboardHistoryPanel.qml"
require 'id: rightPane' "$repo/versions/default/panels/ClipboardHistoryPanel.qml"
require 'TextEdit' "$repo/versions/default/panels/ClipboardHistoryPanel.qml"
require 'Image.PreserveAspectFit' "$repo/versions/default/panels/ClipboardHistoryPanel.qml"
require 'QS_CLIPBOARD_INPUT_DEBUG' "$repo/versions/default/panels/ClipboardHistoryPanel.qml"
require 'Keys.priority: Keys.BeforeItem' "$repo/versions/default/panels/ClipboardHistoryPanel.qml"
require 'elephant query' "$repo/scripts/qs-clipboard.sh"
require 'omarchy-capture-screenshot' "$repo/scripts/qs-capture.sh"
require 'QS_MENU_BEGIN' "$repo/scripts/qs-mode.sh"
require 'qs-clipboard.sh' "$repo/install.sh"
require 'qs-capture.sh' "$repo/install.sh"
require 'qs-clipboard' "$repo/uninstall.sh"
require 'qs-capture' "$repo/uninstall.sh"
require 'x: Math.round\(\(parent.width - width\) / 2\)' "$repo/versions/default/panels/OmarchyMenuPanel.qml"
require 'x: Math.round\(\(parent.width - width\) / 2\)' "$repo/versions/default/panels/ClipboardHistoryPanel.qml"
require 'x: Math.round\(\(parent.width - width\) / 2\)' "$repo/versions/default/panels/CapturePanel.qml"
require 'bind = SUPER, SPACE, exec, qs -c bar ipc call -- launcher open' "$repo/scripts/qs-mode.sh"
require 'binds = Super_L&Alt_R, SPACE' "$repo/scripts/qs-mode.sh"
require 'binds = Super_L&Alt_R, S, movetoworkspacesilent, special:scratchpad' "$repo/scripts/qs-mode.sh"
require 'timeout 0.35 elephant query --async' "$repo/scripts/qs-clipboard.sh"
require 'bindd = , PRINT, Quickshell screenshot, exec, qs-capture screenshot' "$repo/scripts/qs-mode.sh"
require 'bindd = ALT, PRINT, Quickshell screenrecording options, exec, qs -c bar ipc call -- capture recording' "$repo/scripts/qs-mode.sh"
require 'bindd = ALT CTRL, PRINT, Quickshell capture menu' "$repo/scripts/qs-mode.sh"
forbid 'omarchy-menu screenrecord' "$repo/scripts/qs-capture.sh"
echo "ok (native surfaces static contract)"
