#!/usr/bin/env bash
set -euo pipefail
repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
require() { rg -q -- "$1" "$2" || { echo "FAIL: $1 in $2" >&2; exit 1; }; }
forbid() { ! rg -q -- "$1" "$2" || { echo "FAIL: unexpected $1 in $2" >&2; exit 1; }; }
require 'target: "menu"' "$repo/versions/default/shell.qml"
require 'target: "themeSwitcher"' "$repo/versions/default/shell.qml"
require 'target: "wallpaperSwitcher"' "$repo/versions/default/shell.qml"
require 'WallpaperSwitcherPanel' "$repo/versions/default/shell.qml"
require 'openWallpaperSwitcher' "$repo/versions/default/Theme.qml"
require 'function wallpaper\(\): void   \{ openWallpaperSwitcher\(\) \}' "$repo/versions/default/Theme.qml"
require 'open-wallpaper-switcher' "$repo/versions/default/models/OmarchyMenuModel.js"
require 'root.openWallpaperSwitcher()' "$repo/versions/default/panels/OmarchyMenuPanel.qml"
require 'sideCapacity: Math.max' "$repo/versions/default/panels/WallpaperSwitcherPanel.qml"
require 'mask: Region \{ item: body \}' "$repo/versions/default/panels/WallpaperSwitcherPanel.qml"
require 'id: blurSurface' "$repo/versions/default/panels/WallpaperSwitcherPanel.qml"
require 'anchors.fill: parent' "$repo/versions/default/panels/WallpaperSwitcherPanel.qml"
require 'opacity: panel.reveal' "$repo/versions/default/panels/WallpaperSwitcherPanel.qml"
require 'Keys.priority: Keys.BeforeItem' "$repo/versions/default/panels/WallpaperSwitcherPanel.qml"
require 'e.key === Qt.Key_Return \|\| e.key === Qt.Key_Enter' "$repo/versions/default/panels/WallpaperSwitcherPanel.qml"
require 'function cancelAndClose\(\)' "$repo/versions/default/panels/WallpaperSwitcherPanel.qml"
require 'function confirmAndClose\(\)' "$repo/versions/default/panels/WallpaperSwitcherPanel.qml"
require 'cancelProc.command = \["omarchy-theme-bg-set", sessionStartPath\]' "$repo/versions/default/panels/WallpaperSwitcherPanel.qml"
require 'focusItem.focus = false' "$repo/versions/default/panels/WallpaperSwitcherPanel.qml"
forbid 'root.paper.b, 0\.74' "$repo/versions/default/panels/WallpaperSwitcherPanel.qml"
forbid 'root.paper.b, 1' "$repo/versions/default/panels/WallpaperSwitcherPanel.qml"
require 'command = \["omarchy-theme-bg-set", applyingPath\]' "$repo/versions/default/panels/WallpaperSwitcherPanel.qml"
require 'unbind = SUPER CTRL, SPACE' "$repo/scripts/qs-mode.sh"
require 'wallpaperSwitcher toggle' "$repo/scripts/qs-mode.sh"
require 'qs-wallpaper-switcher' "$repo/install.sh"
require 'qs-wallpaper-switcher' "$repo/uninstall.sh"
require 'ensure-hypr-launcher-binding.sh' "$repo/install.sh"
require 'ensure-hypr-launcher-binding.sh' "$repo/uninstall.sh"
require 'ensure-hypr-switcher-blur-rules.sh' "$repo/install.sh"
require 'ensure-hypr-switcher-blur-rules.sh' "$repo/uninstall.sh"
require 'ensure-hypr-switcher-blur-rules.sh' "$repo/scripts/qs-shell-refresh-local.sh"
require 'ensure-hypr-switcher-blur-rules.sh' "$repo/scripts/qs-shell-post-update.sh"
require 'qs-shell-refresh-local.sh' "$repo/install.sh"
require 'qs-shell-refresh-local.sh' "$repo/uninstall.sh"
forbid 'style-background\) exec omarchy-theme-bg-set' "$repo/scripts/qs-menu-action.sh"
forbid 'omarchy-menu background|menus:omarchyBackgroundSelector|Walker' "$repo/versions/default/panels/WallpaperSwitcherPanel.qml"
require 'target: "clipboard"' "$repo/versions/default/shell.qml"
require 'target: "capture"' "$repo/versions/default/shell.qml"
require 'target: "emoji"' "$repo/versions/default/shell.qml"
require 'EmojiPickerPanel' "$repo/versions/default/shell.qml"
require 'Keys.priority: Keys.BeforeItem' "$repo/versions/default/panels/EmojiPickerPanel.qml"
require 'ListView' "$repo/versions/default/panels/EmojiPickerPanel.qml"
require 'qs-emoji.*"select"' "$repo/versions/default/panels/EmojiPickerPanel.qml"
require 'function unicodeLabel' "$repo/versions/default/panels/EmojiPickerPanel.qml"
require 'id: emojiGlyph' "$repo/versions/default/panels/EmojiPickerPanel.qml"
require 'id: codePoint' "$repo/versions/default/panels/EmojiPickerPanel.qml"
require 'color: Qt.rgba\(root.bg.r, root.bg.g, root.bg.b, 1\)' "$repo/versions/default/panels/EmojiPickerPanel.qml"
require 'WheelHandler' "$repo/versions/default/panels/EmojiPickerPanel.qml"
require 'emojiList.contentY = Math.max' "$repo/versions/default/panels/EmojiPickerPanel.qml"
require 'policy: ScrollBar.AlwaysOn' "$repo/versions/default/panels/EmojiPickerPanel.qml"
require 'interactive: true' "$repo/versions/default/panels/EmojiPickerPanel.qml"
forbid 'id: modeRow|panel.modeIndex|panel.modes' "$repo/versions/default/panels/EmojiPickerPanel.qml"
forbid 'Emoji & Symbols|Search emoji|Type to filter|Arrows browse|Enter paste|Esc close' "$repo/versions/default/panels/EmojiPickerPanel.qml"
require 'bindd = SUPER CTRL, E, Quickshell emoji picker' "$repo/scripts/qs-mode.sh"
require 'qs-emoji.sh' "$repo/install.sh"
require 'qs-emoji' "$repo/uninstall.sh"
require 'SelectableList' "$repo/versions/default/panels/OmarchyMenuPanel.qml"
require 'activeMenu === "style.unlocks"' "$repo/versions/default/panels/OmarchyMenuPanel.qml"
require 'previewPath: parts\[5\]' "$repo/versions/default/panels/OmarchyMenuPanel.qml"
require 'sourceSize.width: 624' "$repo/versions/default/panels/OmarchyMenuPanel.qml"
require 'function setFont\(fontName: string\)' "$repo/versions/default/Theme.qml"
require 'omarchy-font-current' "$repo/versions/default/Theme.qml"
require 'export -f omarchy-restart-waybar omarchy-restart-swayosd' "$repo/scripts/qs-menu-action.sh"
require 'orientation: ListView.Horizontal' "$repo/versions/default/panels/ClipboardHistoryPanel.qml"
require 'activeFilter' "$repo/versions/default/panels/ClipboardHistoryPanel.qml"
require 'preview_type' "$repo/versions/default/panels/ClipboardHistoryPanel.qml"
require 'sourceSize.width: 160' "$repo/versions/default/panels/ClipboardHistoryPanel.qml"
require 'editSelectedImage' "$repo/versions/default/panels/ClipboardHistoryPanel.qml"
require 'qs-clipboard.*"edit"' "$repo/versions/default/panels/ClipboardHistoryPanel.qml"
require 'text: "Clipboard History"' "$repo/versions/default/panels/ClipboardHistoryPanel.qml"
require 'pendingSelectionIndex = selectedIndex' "$repo/versions/default/panels/ClipboardHistoryPanel.qml"
require 'TextEdit' "$repo/versions/default/panels/ClipboardHistoryPanel.qml"
require 'Image.PreserveAspectFit' "$repo/versions/default/panels/ClipboardHistoryPanel.qml"
require 'QS_CLIPBOARD_INPUT_DEBUG' "$repo/versions/default/panels/ClipboardHistoryPanel.qml"
require 'Keys.priority: Keys.BeforeItem' "$repo/versions/default/panels/ClipboardHistoryPanel.qml"
require 'elephant query' "$repo/scripts/qs-clipboard.sh"
require 'exec satty --filename' "$repo/scripts/qs-clipboard.sh"
require 'omarchy-capture-screenshot' "$repo/scripts/qs-capture.sh"
require 'open-theme-switcher' "$repo/versions/default/models/OmarchyMenuModel.js"
require 'ThemeSwitcherPanel' "$repo/versions/default/shell.qml"
require 'mask: Region \{ item: card \}' "$repo/versions/default/panels/ThemeSwitcherPanel.qml"
require 'id: blurSurface' "$repo/versions/default/panels/ThemeSwitcherPanel.qml"
require 'anchors.fill: parent' "$repo/versions/default/panels/ThemeSwitcherPanel.qml"
require 'opacity: panel.reveal' "$repo/versions/default/panels/ThemeSwitcherPanel.qml"
require 'Keys.priority: Keys.BeforeItem' "$repo/versions/default/panels/ThemeSwitcherPanel.qml"
require 'event.key === Qt.Key_Return \|\| event.key === Qt.Key_Enter' "$repo/versions/default/panels/ThemeSwitcherPanel.qml"
require 'function cancelAndClose\(\)' "$repo/versions/default/panels/ThemeSwitcherPanel.qml"
require 'function confirmAndClose\(\)' "$repo/versions/default/panels/ThemeSwitcherPanel.qml"
require 'cancelProc.command = \["omarchy-theme-set", sessionStartId\]' "$repo/versions/default/panels/ThemeSwitcherPanel.qml"
require 'focusItem.focus = false' "$repo/versions/default/panels/ThemeSwitcherPanel.qml"
forbid 'root.paper.b, 0\.74' "$repo/versions/default/panels/ThemeSwitcherPanel.qml"
forbid 'root.paper.b, 1' "$repo/versions/default/panels/ThemeSwitcherPanel.qml"
require 'qs-theme-switcher' "$repo/install.sh"
require 'qs-theme-switcher' "$repo/uninstall.sh"
require 'unbind = SUPER CTRL SHIFT, SPACE' "$repo/scripts/qs-mode.sh"
require 'bind = SUPER CTRL SHIFT, SPACE, exec, qs -c bar ipc call themeSwitcher toggle' "$repo/scripts/qs-mode.sh"
require 'Toggle desktop provider, exec, bash -lc' "$repo/scripts/ensure-hypr-launcher-binding.sh"
require '\$\((qs-mode status)\)' "$repo/scripts/ensure-hypr-launcher-binding.sh"
require 'layerrule = blur on, match:namespace quickshell-theme-switcher' "$repo/scripts/ensure-hypr-switcher-blur-rules.sh"
require 'layerrule = ignore_alpha 0, match:namespace quickshell-wallpaper-switcher' "$repo/scripts/ensure-hypr-switcher-blur-rules.sh"
require 'command: \["omarchy-capture-screenrecording", "--stop-recording"\]' "$repo/versions/default/modules/ScreenRecordWidget.qml"
require 'readonly property int titleWidth: 119' "$repo/versions/default/modules/MprisWidget.qml"
require 'id: marqueeClip' "$repo/versions/default/modules/MprisWidget.qml"
require 'id: eqCanvas' "$repo/versions/default/modules/MprisWidget.qml"
require 'current.togglePlaying\(\)' "$repo/versions/default/modules/MprisWidget.qml"
forbid 'player\.previous\(\)|player\.next\(\)|canGoPrevious|canGoNext' "$repo/versions/default/modules/MprisWidget.qml"
forbid 'bash -c.*stop-recording' "$repo/versions/default/modules/ScreenRecordWidget.qml"
forbid 'contentInputPriority' "$repo/versions/default"
forbid 'omarchy-launch-walker.*omarchythemes' "$repo/versions/default"
require 'QS_MENU_BEGIN' "$repo/scripts/qs-mode.sh"
require 'qs-clipboard.sh' "$repo/install.sh"
require 'qs-capture.sh' "$repo/install.sh"
require 'qs-clipboard' "$repo/uninstall.sh"
require 'qs-capture' "$repo/uninstall.sh"
require 'x: Math.round\(\(parent.width - width\) / 2\)' "$repo/versions/default/panels/OmarchyMenuPanel.qml"
require 'x: Math.round\(\(parent.width - width\) / 2\)' "$repo/versions/default/panels/ClipboardHistoryPanel.qml"
require 'x: Math.round\(\(parent.width - width\) / 2\)' "$repo/versions/default/panels/CapturePanel.qml"
require 'bind = SUPER, SPACE, exec, qs -c bar ipc call -- launcher open' "$repo/scripts/qs-mode.sh"
require 'binds = Super_L&Alt_R, SPACE' "$repo/scripts/qs-mode.sh"
require 'binds = Super_L&Alt_R, S, movetoworkspacesilent, special:scratchpad' "$repo/scripts/qs-mode.sh"
require 'timeout 0.6 elephant query --async' "$repo/scripts/qs-clipboard.sh"
require 'bindd = , PRINT, Quickshell screenshot, exec, qs-capture screenshot' "$repo/scripts/qs-mode.sh"
require 'bindd = ALT, PRINT, Quickshell screenrecording options, exec, qs -c bar ipc call -- capture recording' "$repo/scripts/qs-mode.sh"
require 'bindd = ALT CTRL, PRINT, Quickshell capture menu' "$repo/scripts/qs-mode.sh"
forbid 'omarchy-menu screenrecord' "$repo/scripts/qs-capture.sh"
echo "ok (native surfaces static contract)"
