#!/usr/bin/env bash
set -euo pipefail
repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
require() { rg -q -- "$1" "$2" || { echo "FAIL: $1 in $2" >&2; exit 1; }; }
forbid() { ! rg -q -- "$1" "$2" || { echo "FAIL: unexpected $1 in $2" >&2; exit 1; }; }
manager="$repo/versions/default/NotificationManager.qml"
toast="$repo/versions/default/NotificationToastOverlay.qml"
osd="$repo/versions/default/HardwareOsdOverlay.qml"
require 'NotificationServer' "$manager"
require 'notification.transient' "$manager"
require 'notification.expireTimeout' "$manager"
require 'NotificationUrgency.Critical' "$manager"
require 'if \(toasts\[i\].key === entry.key\)' "$manager"
require 'result.length < 4' "$manager"
require 'Hyprland.focusedMonitor' "$manager"
require 'x-quickshell-osd-kind' "$manager"
require 'bodyHyperlinksSupported: false' "$manager"
require 'actionIconsSupported: false' "$manager"
require 'width: 380' "$toast"
require 'parent.width - width - 12' "$toast"
require 'barReservedExtent \+ 12' "$toast"
require 'mask: Region \{ item: cards \}' "$toast"
require 'toLowerCase\(\) !== "notify-send"' "$toast"
require 'visible: toastCard.showAppName' "$toast"
require 'mask: Region \{\}' "$osd"
require 'brightnessScale: 1.5' "$osd"
require 'brightnessWidth: 72 \* brightnessScale' "$osd"
require 'brightnessHeight: 64 \* brightnessScale' "$osd"
require 'card.brightnessEvent \? overlay.brightnessWidth' "$osd"
require 'Math.min\(300, Math.max\(190, row.implicitWidth \+ 30\)\)' "$osd"
require 'placementRatio: 0.70' "$osd"
require 'usableHeight \* placementRatio' "$osd"
require 'Math.max\(minimumOsdY, Math.min\(maximumOsdY, desiredOsdY\)\)' "$osd"
require 'segmentCount: 14' "$osd"
require 'leadingEdge' "$osd"
require 'brightnessEvent: root.osdKind === "brightness"' "$osd"
require 'rayCount: 16' "$osd"
require 'leadingRay' "$osd"
require 'card.percentageEvent && !card.brightnessEvent' "$osd"
require 'visible: !card.brightnessEvent' "$osd"
require 'visible: root.osdValue !== "" && !card.brightnessEvent' "$osd"
require 'cameraEvent: root.osdKind === "camera"' "$osd"
require 'card.cameraEvent \? 60' "$osd"
require 'mediaEvent: root.osdKind === "media"' "$osd"
require 'card.mediaEvent \? 300' "$osd"
require 'mediaLines: root.osdDetail.split\("\\n"\)' "$osd"
require 'mediaTitle: mediaLines.length > 0' "$osd"
require 'mediaArtist: mediaLines.length > 1' "$osd"
require 'visible: card.mediaEvent' "$osd"
require 'width: 230' "$osd"
require 'clip: true' "$osd"
require 'text: card.mediaTitle' "$osd"
require 'text: card.mediaArtist' "$osd"
require 'font.pixelSize: 13' "$osd"
require 'font.weight: Font.DemiBold' "$osd"
require 'font.pixelSize: 12' "$osd"
require 'IconMap.icon\(card.cameraEnabled \? "videocam" : "videocam_off"\)' "$osd"
require 'visible: !card.brightnessEvent && !card.cameraEvent' "$osd"
require 'visible: !card.cameraEvent' "$osd"
forbid 'text:.*Camera enabled|text:.*Camera disabled|text:.*Camera blocked' "$osd"
require 'anchors.centerIn: burstCore' "$osd"
require 'color: card.brightnessEvent \? "transparent" : root.paper' "$osd"
require 'border.width: card.brightnessEvent \? 0 : root.pillBorderW' "$osd"
require 'PillShadow \{ theme: root; visible: !card.brightnessEvent \}' "$osd"
require 'text: Math.round\(card.percentage\)' "$osd"
require 'width: 30 \* overlay.brightnessScale' "$osd"
require 'root.paper.b, 0.72' "$osd"
require 'anchors.verticalCenterOffset: -1' "$osd"
require 'width: 34 \* overlay.brightnessScale' "$osd"
require 'font.pixelSize: 12 \* overlay.brightnessScale' "$osd"
require 'font.weight: Font.DemiBold' "$osd"
require 'font.letterSpacing: 0' "$osd"
require 'font.features: \(\{ "tnum": 1 \}\)' "$osd"
require 'horizontalAlignment: Text.AlignHCenter' "$osd"
forbid 'id: fill|Behavior on width' "$osd"
require 'interval: 1200' "$repo/versions/default/Theme.qml"
require 'ipc call -- osd show' "$repo/scripts/qs-rise-input.sh"
require 'playerctl metadata --format' "$repo/scripts/qs-rise-input.sh"
require 'xesam:title.*xesam:artist' "$repo/scripts/qs-rise-input.sh"
require 'detail="\$title"\$'"'"'\\n'"'"'"\$artist"' "$repo/scripts/qs-rise-input.sh"
require 'show_osd media "" "\$detail" "󰎈"' "$repo/scripts/qs-rise-input.sh"
forbid 'show_osd media "" "\$1"' "$repo/scripts/qs-rise-input.sh"
forbid 'qs-rise-osd.json' "$repo/install.sh"
forbid 'quickshell-pulse|PulseOverlay|modules/Pulse.qml' "$repo/versions/default"
echo "ok (notification and OSD static contract)"
