.pragma library

// This is the Quickshell-owned menu tree.  It contains presentation data and
// stable action IDs only; backend command execution remains in
// scripts/qs-menu-action.sh.  Submenus are data, never commands.
var menus = { root: [] }
var menuInfo = { root: { id: "root", label: "Menu", type: "submenu" } }

function addMenu(id, parent, label, icon, detail) {
    var entry = {
        id: id,
        icon: icon || "•",
        label: label,
        detail: detail || "",
        type: "submenu",
        submenuId: id
    }
    if (!menus[parent]) menus[parent] = []
    menus[parent].push(entry)
    if (!menus[id]) menus[id] = []
    menuInfo[id] = { id: id, label: label, type: "submenu" }
}

function addAction(id, parent, label, icon, actionId) {
    var entry = {
        id: id,
        icon: icon || "•",
        label: label,
        type: "action",
        actionId: actionId || id
    }
    if (!menus[parent]) menus[parent] = []
    menus[parent].push(entry)
}

function addGroup(id, parent, label) {
    addMenu(id, parent, label, "•")
}

function addLeaves(parent, labels, actionPrefix) {
    for (var i = 0; i < labels.length; i++) {
        var id = parent + "." + labels[i].toLowerCase().replace(/[^a-z0-9]+/g, "-")
        addAction(id, parent, labels[i], "•", actionPrefix + "-" + id.slice(parent.length + 1))
    }
}

// Root menu.  Icons, labels, and details intentionally match the existing UI.
addAction("apps", "root", "Apps", "󰀻", "open-app-launcher")
addMenu("trigger", "root", "Trigger", "󱓞", "Capture, share and toggles")
addMenu("style", "root", "Style", "", "Theme, wallpaper and appearance")
addMenu("setup", "root", "Setup", "", "Devices and configuration")
addMenu("install", "root", "Install", "󰉉", "Packages and applications")
addMenu("remove", "root", "Remove", "󰭌", "Uninstall applications and features")
addMenu("update", "root", "Update", "", "System and service updates")
addAction("about", "root", "About", "", "open-about")
addMenu("system", "root", "System", "", "Power and session")

// Trigger
addMenu("trigger.reminder", "trigger", "Reminder", "󰔛")
addMenu("trigger.capture", "trigger", "Capture", "")
addAction("trigger.transcode", "trigger", "Transcode", "󰧸", "trigger-transcode")
addMenu("trigger.share", "trigger", "Share", "")
addMenu("trigger.toggle", "trigger", "Toggle", "󰔎")
addMenu("trigger.hardware", "trigger", "Hardware", "")
addAction("trigger.capture.screenshot", "trigger.capture", "Screenshot", "", "capture-screenshot")
addAction("trigger.capture.screenrecord", "trigger.capture", "Screenrecord", "", "capture-screenrecord")
addAction("trigger.capture.text", "trigger.capture", "Text Extraction", "󰴑", "capture-text")
addAction("trigger.capture.color", "trigger.capture", "Color", "󰃉", "capture-color")
addAction("trigger.reminder.set", "trigger.reminder", "Set one", "󰔛", "reminder-set")
addAction("trigger.reminder.show", "trigger.reminder", "Show all", "󰔛", "reminder-show")
addAction("trigger.reminder.clear", "trigger.reminder", "Clear all", "󰔛", "reminder-clear")
addAction("trigger.share.clipboard", "trigger.share", "Clipboard", "", "share-clipboard")
addAction("trigger.share.file", "trigger.share", "File", "", "share-file")
addAction("trigger.share.folder", "trigger.share", "Folder", "", "share-folder")

// System
addAction("system.screensaver", "system", "Screensaver", "󱄄", "system-screensaver")
addAction("system.lock", "system", "Lock", "", "system-lock")
addAction("system.suspend", "system", "Suspend", "󰒲", "system-suspend")
addAction("system.hibernate", "system", "Hibernate", "󰤁", "system-hibernate")
addAction("system.logout", "system", "Logout", "󰍃", "system-logout")
addAction("system.restart", "system", "Restart", "󰜉", "system-restart")
addAction("system.shutdown", "system", "Shutdown", "󰐥", "system-shutdown")

// Style
addGroup("style.theme", "style", "Theme")
// Unlocks are generated by an upstream Walker provider. Represent the
// provider boundary as a normal Quickshell submenu, never an external menu.
addGroup("style.unlocks", "style", "Unlock")
addAction("style.background", "style", "Background", "•", "style-background")
addAction("style.hyprland", "style", "Hyprland", "•", "style-hyprland")
addGroup("style.font", "style", "Font")
addGroup("style.screensaver", "style", "Screensaver")
addGroup("style.about", "style", "About")
for (var styleLeaf of ["Edit Text", "Set From Image", "Restore Default"]) {
    var styleId = styleLeaf.toLowerCase().replace(/ /g, "-")
    addAction("style.screensaver." + styleId, "style.screensaver", styleLeaf, "•", "style-screensaver-" + styleId)
    addAction("style.about." + styleId, "style.about", styleLeaf, "•", "style-about-" + styleId)
}

// Setup
for (var setup of ["Audio", "Wifi", "Bluetooth", "Monitors", "Keybindings", "Input", "DNS"])
    addAction("setup." + setup.toLowerCase().replace(/ /g, "-"), "setup", setup, "•", "setup-" + setup.toLowerCase().replace(/ /g, "-"))
addGroup("setup.power-profile", "setup", "Power Profile")
for (var profile of ["Performance", "Balanced", "Power Saver"])
    addAction("setup.power-profile." + profile.toLowerCase().replace(/ /g, "-"), "setup.power-profile", profile, "•", "setup-power-profile-" + profile.toLowerCase().replace(/ /g, "-"))
addAction("setup.system-sleep", "setup", "System Sleep", "•", "setup-system-sleep")
addGroup("setup.defaults", "setup", "Defaults")
addGroup("setup.security", "setup", "Security")
addGroup("setup.config", "setup", "Config")
for (var config of ["Hyprland", "Hypridle", "Hyprlock", "Hyprsunset", "SwayOSD", "Walker", "Waybar", "XCompose"])
    addAction("setup.config." + config.toLowerCase(), "setup.config", config, "•", "setup-config-" + config.toLowerCase())
for (var security of ["Fingerprint", "Fido2"])
    addAction("setup.security." + security.toLowerCase(), "setup.security", security, "•", "setup-security-" + security.toLowerCase())
for (var def of ["Browser", "Terminal", "Editor"])
    addGroup("setup.defaults." + def.toLowerCase(), "setup.defaults", def)
addLeaves("setup.defaults.browser", ["Chrome", "Edge", "Brave", "Brave Origin", "Firefox", "Zen"], "setup-default-browser")
addLeaves("setup.defaults.terminal", ["Alacritty", "Foot", "Ghostty", "Kitty"], "setup-default-terminal")
addLeaves("setup.defaults.editor", ["Neovim", "VSCode", "Cursor", "Zed", "Sublime", "Helix", "Vim", "Emacs"], "setup-default-editor")

// Install
addAction("install.package", "install", "Package", "•", "install-package")
addAction("install.aur", "install", "AUR", "•", "install-aur")
addAction("install.web-app", "install", "Web App", "•", "install-web-app")
addAction("install.tui", "install", "TUI", "•", "install-tui")
for (var installGroup of ["Service", "Style", "Development", "Editor", "Terminal", "Browser", "AI", "Gaming"])
    addGroup("install." + installGroup.toLowerCase().replace(/ /g, "-"), "install", installGroup)
addAction("install.windows", "install", "Windows", "•", "install-windows")
addLeaves("install.service", ["Dropbox", "Tailscale", "NordVPN", "ONCE", "Bitwarden", "Chromium Account"], "install-service")
addLeaves("install.style", ["Theme", "Background", "Font"], "install-style")
addLeaves("install.development", ["Ruby on Rails", "Docker DB", "JavaScript", "Go", "PHP", "Python", "Elixir", "Zig", "Rust", "Java", ".NET", "OCaml", "Clojure", "Scala"], "install-development")
addLeaves("install.editor", ["VSCode", "Cursor", "Zed", "Sublime Text", "Helix", "Vim", "Emacs"], "install-editor")
addLeaves("install.terminal", ["Alacritty", "Foot", "Ghostty", "Kitty"], "install-terminal")
addLeaves("install.browser", ["Chrome", "Edge", "Brave", "Brave Origin", "Firefox", "Zen"], "install-browser")
addLeaves("install.ai", ["Dictation", "LM Studio", "Ollama", "Crush"], "install-ai")
addLeaves("install.gaming", ["Steam", "RetroArch", "Minecraft", "NVIDIA GeForce NOW", "Xbox Cloud Gaming", "Xbox Controller", "Moonlight", "Lutris", "Heroic"], "install-gaming")

// Remove
addAction("remove.package", "remove", "Package", "•", "remove-package")
addAction("remove.web-app", "remove", "Web App", "•", "remove-web-app")
addAction("remove.tui", "remove", "TUI", "•", "remove-tui")
for (var removeGroup of ["Development", "Theme", "Browser", "Dictation", "Gaming"])
    addGroup("remove." + removeGroup.toLowerCase().replace(/ /g, "-"), "remove", removeGroup)
addAction("remove.windows", "remove", "Windows", "•", "remove-windows")
addAction("remove.preinstalls", "remove", "Preinstalls", "•", "remove-preinstalls")
addGroup("remove.security", "remove", "Security")
addLeaves("remove.development", ["Ruby on Rails", "JavaScript", "Go", "PHP", "Python", "Elixir", "Zig", "Rust", "Java", ".NET", "OCaml", "Clojure", "Scala"], "remove-development")
addLeaves("remove.browser", ["Chrome", "Edge", "Brave", "Brave Origin", "Firefox", "Zen"], "remove-browser")
addLeaves("remove.gaming", ["Steam", "RetroArch", "Minecraft", "NVIDIA GeForce NOW", "Xbox Cloud Gaming", "Xbox Controller", "Moonlight", "Lutris", "Heroic"], "remove-gaming")

// Update
for (var updateAction of ["Omarchy", "Extra Themes", "Firmware", "Password", "Timezone", "Time"])
    addAction("update." + updateAction.toLowerCase().replace(/ /g, "-"), "update", updateAction, "•", "update-" + updateAction.toLowerCase().replace(/ /g, "-"))
for (var updateGroup of ["Channel", "Config", "Process", "Hardware"])
    addGroup("update." + updateGroup.toLowerCase().replace(/ /g, "-"), "update", updateGroup)
addLeaves("update.channel", ["Stable", "RC", "Edge", "Dev"], "update-channel")
addLeaves("update.config", ["Hyprland", "Hypridle", "Hyprlock", "Hyprsunset", "Plymouth", "SwayOSD", "Tmux", "Walker", "Waybar"], "update-config")
addLeaves("update.process", ["Hypridle", "Hyprsunset", "Mako", "SwayOSD", "Walker", "Waybar"], "update-process")
addLeaves("update.hardware", ["Audio", "Wi-Fi", "Bluetooth", "Trackpad"], "update-hardware")

// Screen-recording choices are actions, not a second menu engine.
for (var captureMode of ["With no audio", "With desktop audio", "With desktop + microphone audio", "With desktop + microphone audio + webcam"]) {
    var captureId = captureMode.toLowerCase().replace(/[^a-z]+/g, "-")
    addAction("trigger.capture.recording." + captureId, "trigger.capture", captureMode, "•", "capture-screenrecord")
}

function children(id) {
    return menus[id] || []
}

function find(id) {
    return menuInfo[id] || null
}
